[FEATURE] Search history
ISIS3510-202410-Team23/SwiftApp pull request #127
Opened 2024-04-23 20:02 UTC by juanyepesp

CLOSES #94 

- This saves in local storage using a .json file the search history of the user, while showing it to them. 
- It only does so when the user hits the "search" button on the keyboard

https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/16772789-a7e8-428a-8e99-be26182b3a72

2024-04-23 21:18 UTC, mar-cas3 submitted a review, later dismissed
Great, thank you!!
![beyonce kick GIF](https://media0.giphy.com/media/n8Vkqvs3r4WXu/giphy.gif)

2024-04-23 21:26 UTC, Laurarestrepo03 commented
I have a question. I'm on my phone so I've only skimmed the code, but I'm curious to know when a search is added to history, when clicking search or when clicking on a spot after searching?

2024-04-23 21:31 UTC, mar-cas3 commented
@juanyepesp just realized something, not sure if you implemented, i'll check the code and delete if so, but if you log in with another user are the recent searches reset?

2024-04-23 23:30 UTC, juanyepesp commented
> I have a question. I'm on my phone so I've only skimmed the code, but I'm curious to know when a search is added to history, when clicking search or when clicking on a spot after searching?

@Laurarestrepo03 as I said it only saves when hitting the search, this is the way flutter has it implemented as well

2024-04-23 23:31 UTC, juanyepesp commented
> @juanyepesp just realized something, not sure if you implemented, i'll check the code and delete if so, but if you log in with another user are the recent searches reset?
> 
> Edit: I tested locally to check and the recents are the same with different accounts. I think you should reset the file once a user logs out so this doesn't happen (seems easier than keeping file x user and makes sense that they'll be reset at this point)

@mar-cas3 should the file be reset every new log in or should the search history be saved by user?

2024-04-23 23:33 UTC, Laurarestrepo03 commented
> > I have a question. I'm on my phone so I've only skimmed the code, but I'm curious to know when a search is added to history, when clicking search or when clicking on a spot after searching?
> 
> @Laurarestrepo03 as I said it only saves when hitting the search, this is the way flutter has it implemented as well

Thanks! Sorry btw, was checking the PR on my phone and must've missed that part 😬

2024-04-23 23:34 UTC, juanyepesp commented
> > > I have a question. I'm on my phone so I've only skimmed the code, but I'm curious to know when a search is added to history, when clicking search or when clicking on a spot after searching?
> > 
> > 
> > @Laurarestrepo03 as I said it only saves when hitting the search, this is the way flutter has it implemented as well
> 
> Thanks! Sorry btw, was checking the PR on my phone and must've missed that part 😬

No worries!! I was debating if it should be in both cases, so I might change it if I figure out how to do it!

2024-04-23 23:35 UTC, Laurarestrepo03 commented
> > @juanyepesp just realized something, not sure if you implemented, i'll check the code and delete if so, but if you log in with another user are the recent searches reset?
> > Edit: I tested locally to check and the recents are the same with different accounts. I think you should reset the file once a user logs out so this doesn't happen (seems easier than keeping file x user and makes sense that they'll be reset at this point)
> 
> @mar-cas3 should the file be reset every new log in or should the search history be saved by user?

Just squeezing in here but maybe you can do what do and reset the file with every _log out_. I think saving by user might be storing sentive information (at least that's the argument for the reason I did my features that way)

2024-04-23 23:36 UTC, Laurarestrepo03 requested changes
I'm requesting the same change as @mar-cas3

2024-04-23 23:36 UTC, juanyepesp commented
> > > @juanyepesp just realized something, not sure if you implemented, i'll check the code and delete if so, but if you log in with another user are the recent searches reset?
> > > Edit: I tested locally to check and the recents are the same with different accounts. I think you should reset the file once a user logs out so this doesn't happen (seems easier than keeping file x user and makes sense that they'll be reset at this point)
> > 
> > 
> > @mar-cas3 should the file be reset every new log in or should the search history be saved by user?
> 
> Just squeezing in here but maybe you can do what I do and reset the file with every _log out_. I think saving by user might be storing sentive information (at least that's the argument for the reason I did my features that way)

@Laurarestrepo03 Alrighty, this feedback is very much appreciated! I'll look into making this changes ASAP.

2024-04-23 23:38 UTC, Laurarestrepo03 commented
> > > > @juanyepesp just realized something, not sure if you implemented, i'll check the code and delete if so, but if you log in with another user are the recent searches reset?
> > > > Edit: I tested locally to check and the recents are the same with different accounts. I think you should reset the file once a user logs out so this doesn't happen (seems easier than keeping file x user and makes sense that they'll be reset at this point)
> > > 
> > > 
> > > @mar-cas3 should the file be reset every new log in or should the search history be saved by user?
> > 
> > 
> > Just squeezing in here but maybe you can do what I do and reset the file with every _log out_. I think saving by user might be storing sentive information (at least that's the argument for the reason I did my features that way)
> 
> @Laurarestrepo03 Alrighty, this feedback is very much appreciated! I'll look into making this changes ASAP.

I edited my comment just now, be sure to check out the new version!

2024-04-23 23:39 UTC, juanyepesp commented
@Laurarestrepo03 
>Unless you don't store by user locally and fetch it with every log in

Could you clarify what you mean by this?

2024-04-23 23:43 UTC, Laurarestrepo03 commented
> @Laurarestrepo03
> 
> > Unless you don't store by user locally and fetch it with every log in
> 
> Could you clarify what you mean by this?

Ofc, wrote it in a bit of a rush but I was thinking maybe you can save the history locally, but once the user logs out send it to firestore, that way when they log back in they can access it again. This is very **extra**  but it's just an idea if you actually wanna save by user, if not you can just delet when they log out and never recover the previous info.

2024-04-24 14:00 UTC, juanyepesp commented
@mar-cas3 @Laurarestrepo03 With these changes, signing out will delete the document and therefore the search history.

2024-04-24 14:19 UTC, mar-cas3 approved these changes
Everything 🆗 !
<img width = "200" src="https://media2.giphy.com/media/l396UAoBXDmTroDT2/giphy.gif">

2024-04-24 16:13 UTC, Laurarestrepo03 approved these changes

2024-04-24 16:13 UTC, Laurarestrepo03 commented on FoodBookApp/UI/Views/User/UserView.swift
> +                        try FileManager.default.removeItem(at: fileURL)
Nice!

2024-04-24 16:25 UTC, merged