[Feature] Add firebase to ios project
ISIS3510-202410-Team23/SwiftApp pull request #19
Opened 2024-02-25 02:26 UTC by mar-cas3

Followed this guide: https://firebase.google.com/docs/ios/setup

* Adds google configuration file + SDK packages as dependencies to project.
* Configures the entry point of the app to use Firebase (see [FoodBookApp.swift](./FoodBookApp/FoodBookApp.swift))

Additionally, configured to use Analytics packages for future implementation. 
![Screenshot 2024-02-24 at 9 18 53 PM](https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/9a777761-2ec8-4c0e-8bc5-8401953e9d48)

Closes #18

2024-02-25 17:06 UTC, mar-cas3 commented
Looking into merge conflict...

2024-02-26 19:54 UTC, juanyepesp requested changes
Pls include usage of the SDK. Thanks!

2024-02-26 19:54 UTC, juanyepesp commented on FoodBookApp/FoodBookApp.swift
> +    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
How can we use this? Maybe document for future reference?

2024-02-27 02:00 UTC, juanyepesp approved these changes
awesome! thanks for including example. 😄

2024-02-27 02:02 UTC, merged