feat: created respective components
ISIS3510-202410-Team23/SwiftApp pull request #20
Opened 2024-02-26 03:11 UTC by juanyepesp

New components added (just views, no functionality):
 - `SpotCard`: Creates a card for the spot
 - `HorCategoryList`:  Lists some categories, is not very responsive or scrollable atm.

Also the browse view shows usage of the components.

closes #6 

<img width="351" alt="Screenshot 2024-02-25 at 10 10 08 PM" src="https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/71ba46a5-8117-4a44-8970-410b03b53070">

2024-02-26 12:21 UTC, mar-cas3 requested changes
Looks good, I would leave a basic ViewModel implemented for now, so just the get() method that returns a hardcoded list so later on when integrating Firebase it's a matter of changing only that code.

2024-02-26 12:49 UTC, juanyepesp commented on FoodBookApp/UI/Components/HorCategoryList.swift
> +struct HorCategoryList: View {
Horizontal JSJSJS maybe I should choose another name

2024-02-26 12:51 UTC, mar-cas3 commented on FoodBookApp/UI/Components/HorCategoryList.swift
> +struct HorCategoryList: View {
Maybe `HCategoryList`, like `HStack` in the SwiftUI components??

2024-02-27 02:09 UTC, mar-cas3 approved these changes
Looks good!

2024-02-27 02:13 UTC, juanyepesp commented
> Looks good!

Not closing yet for merging with latest Develop changes, will ask for future revisions

2024-02-29 17:46 UTC, Laurarestrepo03 commented
Question: isn't search bar missing?

2024-02-29 19:58 UTC, mar-cas3 commented
@juanyepesp was able to resolve conflicts, feel to to merge onto develop when you're ready

2024-02-29 20:09 UTC, merged

2024-02-29 20:28 UTC, juanyepesp commented
@Laurarestrepo03 
> Question: isn't search bar missing?

Yes but since it is not a feature atm I will leave it like this for now